import { ChildrenProps } from '@/types/ChildrenProps'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SearchBar from '@/components/SearchBar'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: ChildrenProps ){
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='p-4 flex justify-around'>
          <Link href="/home">Home</Link>
          <Link href='/users'>Users</Link>
          <Link href='/posts'>Posts</Link>
          <SearchBar />
        </nav>
        {children}
      </body>
    </html>
  )
}
